### ISSUE TITLE
Modify Survivor Class - Add Random Weapon Generation

### ISSUE THREAD

**Issue by JasonLConcordiaSTP** [JasonLConcordiaSTP/ZombieWar#23]

**Comment by wkndevguy** [comment]
We can't have the random weapon creation method in the Abstract parent Survivor class because Weapon can't be instantiated in an abstract class. Random Weapon selection and instantiation should either be implemented in the Survivor factory static class in the game method, or alternatively in the child classes inheriting from Survivor as part of the constructor. I.E.
`Soldier() {`
`this.health = 100;`
`this.damage = <some int>;`
`this.weapon = createRandomWeapon();`
`}`

I would vote for having this in the game class's Survivor factory
